version: '3.7'

services:
  back-end: 
    container_name: 'simple-db-monitor-backend'
    image: 'onkitdev/simple-db-monitor-be'
    build: .
    expose: 
      - "8081"
    ports: 
      - "8081:80"
    volumes:
      - api:/app
    depends_on:
      - postgres-local
    networks:
      - local-network

  postgres-local:
    image: 'postgres:latest'
    container_name: 'postgresql-db'
    ports:
      - "5433:5433"
    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:  
      - db_postgres:/var/lib/postgresql/data
    networks:
      - local-network

volumes:
  api:
  db_postgres:

networks: 
  local-network:
    driver: bridge