---
server:
  host: "192.168.2.132:8180"
  database:
    postgres:
      name: postgres
      enable: true
      uri: "postgresql://postgres:postgres@localhost/Coba"
    redis:
      name: redis
      enable: true
      uri: "localhost:6379"
    mongo:
      name: mongo
      enable: false
      uri: "localhost:27017"
    mysql:
      name: mysql
      enable: false
      uri: root@tcp(localhost:3306)/test
  route:
    - redis
    - postgres
    - mongo
    - mysql
    - user

client:
  host: "192.168.2.132:8080"
  allowed_cors:
    - "http://192.168.2.132:8080"
---